apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    basicAuth: true
    basicAuthUser: $__env{PROMETHEUS_BASIC_AUTH_USER}
    secureJsonData:
      basicAuthPassword: $__env{PROMETHEUS_BASIC_AUTH_PASSWORD}
